### ISSUE TITLE
[Feature request] Folia support

### ISSUE THREAD

**Issue by LuluxClient** [Emibergo02/RedisChat#1]
On the page it's saying it accepts any fork but folia doesn't work, it would be cool to add papermc latest software support to this awesome chat plugin !

**Comment by Emibergo02** [comment]
Yep. I hope i can do it soon. i'm very busy rn

**Comment by Emibergo02** [comment]
I can't do it until PlaceholderAPI will support Folia

**Comment by LuluxClient** [comment]
There is a fork available if needed that works fine

Le mar. 12 sept. 2023 à 11:52, Emibergo02 ***@***.***> a
écrit :
