### ISSUE TITLE
Feature request of show item name based on client-side language chosen

### ISSUE THREAD

**Issue by kit8379** [Emibergo02/RedisChat#10]
As title, so that we don't need to translate all the item names in each update and the user can see the language of the item that their client using. This can be achieved by using minimessage https://docs.advntr.dev/minimessage/format.html#translatable but the internal plugin placeholder %item_name% is not enough ability to use this minimessage tag.

Related Discord Thread:
https://discord.com/channels/1136193314002059356/1192741066919641138

**Comment by Emibergo02** [comment]
Fixed thanks to @rudde0
