### ISSUE TITLE
%player% placeholder doesn't work properly

### ISSUE THREAD

**Issue by DaddyRobLIVE** [Emibergo02/RedisChat#11]
I wanted to show player ping by using the placeholder feature of the plugin

Code:
```
placeholders:
  <ping>: '&a%player_ping%ms'
```
![image](https://github.com/Emibergo02/RedisChat/assets/109517972/c3f62fe1-fdbf-4469-8851-199c9b05aa97)

Output
>  ms
![image](https://github.com/Emibergo02/RedisChat/assets/109517972/af10d786-d00a-4812-ac15-be9f7e847593)

Supposed Output
> 10ms

Observation:
It looks like the plugin is not parsing the %player% properly

**Comment by Emibergo02** [comment]
This is fixed in the latest version
